# Generated by Django 3.0.7 on 2020-07-15 10:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('sylhet', django.db.models.manager.Manager()),
            ],
        ),
    ]
